return {
	name = "body_t",
	size = 296,
	fields = {
		epoch = {type="double", offset=0, size=8, },
		perihelionDistance = {type="double", offset=8, size=8, },
		semiMajorAxis = {type="double", offset=16, size=8, },
		eccentricity = {type="double", offset=24, size=8, },
		inclination = {type="double", offset=32, size=8, },
		argumentOfPeriapsis = {type="double", offset=40, size=8, },
		longitudeOfAscendingNode = {type="double", offset=48, size=8, },
		meanAnomalyAtEpoch = {type="double", offset=56, size=8, },
		absoluteMagnitude = {type="double", offset=64, size=8, },
		magnitudeSlopeParameter = {type="double", offset=72, size=8, },
		timeOfPerihelionPassage = {type="double", offset=80, size=8, },
		bodyType = {type="int", offset=88, size=4, },
		horizonID = {type="int", offset=92, size=4, },
		name = {type="char[44]", offset=96, size=44, },
		orbitSolutionReference = {type="char[13]", offset=140, size=13, },
		index = {type="long", offset=156, size=4, },
		pos = {type="double[3]", offset=160, size=24, },
		vel = {type="double[3]", offset=184, size=24, },
		A = {type="double[3]", offset=208, size=24, },
		B = {type="double[3]", offset=232, size=24, },
		eccentricAnomaly = {type="double", offset=256, size=8, },
		timeOfPeriapsisCrossing = {type="double", offset=264, size=8, },
		meanAnomaly = {type="double", offset=272, size=8, },
		orbitType = {type="int", offset=280, size=4, },
		orbitalPeriod = {type="double", offset=288, size=8, },
	},
}
